### ISSUE TITLE
Zed_cursor.Out_of_bounds when using j in vi mode

### ISSUE THREAD

**Issue by dunrix** [ocaml-community/lambda-term#115]
When `edit_mode_vi` is set, moving cursor in a down direction crashes utop with

> Fatal error: exception Zed_cursor.Out_of_bounds

How to replicate:

1.  set "#edit_mode_vi" option in ~/.config/utop/init.ml
2.  launch utop REPL
3.  at prompt press `Escape` to enter *normal mode*
4.  press `j` to move cursor in a down direction
5. get the exception which terminates utop process

**Comment by kandu** [comment]
This issue should be fixed with PR #116
