### ISSUE TITLE
update from jbuilder to dune

### ISSUE THREAD

**Issue by pmetzger** [ocaml-community/lambda-term#67]
Not an enormous rush, but it would be good to update this from jbuilder to dune.

**Comment by diml** [comment]
I believe this is done since #64

**Comment by pmetzger** [comment]
It has! My mistake!

**Comment by pmetzger** [comment]
It would still be nice to finish porting the documentation generation as well, but that would be a distinct issue. :)

**Comment by diml** [comment]
This should already work actually as `dune build @doc` should do the right thing by default :) We might just need to add a `doc:` field to the opam file so that `dune-release publish` updates the github pages as well.

**Comment by diml** [comment]
Indeed, we should probably update the readme to replace all the calls to `make` by calls to `dune`

**Comment by pmetzger** [comment]
I'll open a new issue.

**Comment by pmetzger** [comment]
Or actually, could you just do it? I would, but I am not able to do git stuff this morning.

**Comment by diml** [comment]
I opened #68 to track the issue. (I would have done the PR directly, but I'm about to leave and it seems that some of the change will require to think)
