### ISSUE TITLE
Windows terminal emulation not supported

### ISSUE THREAD

**Issue by Chimrod** [ocaml-community/lambda-term#75]
Hello, I do not know if this issue is related to #72 or this is caused by a wrong escape sequences.

This is what I got by running utop on a windows terminal :

![2019-06-14_11h19_50](https://user-images.githubusercontent.com/555440/59498933-a53d3000-8e96-11e9-8398-e0936cf95a1a.png)

(utop compiled with the mingw libraries, using [ocaml for windows](https://fdopen.github.io/opam-repository-mingw/))

**Comment by kandu** [comment]
issue reproduced

**Comment by kandu** [comment]
<details><summary>as a result</summary>

![lambda-term](https://user-images.githubusercontent.com/357626/59549588-87ed8c00-8f92-11e9-8198-afa1a809782c.png)
</details>

**Comment by Chimrod** [comment]
Thanks a lot :)
